spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: bookuser
    password: bookpass
    driver-class-name: oracle.jdbc.OracleDriver

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080