CREATE OR REPLACE TRIGGER TRG_BOOKS_AUDIT
AFTER INSERT ON BOOKS
FOR EACH ROW
BEGIN
INSERT INTO AUDIT_LOGS (
    TABLE_NAME,
    ACTION_TYPE,
    LOG_DATE,
    DB_USER
)
VALUES (
           'BOOKS',
           'INSERT',
           SYSTIMESTAMP,
           USER
       );
END;
/