CREATE OR REPLACE PACKAGE BODY BOOK_OPERATIONS AS
       FUNCTION PARSE_TO_XML(
    P_RAW_DATA IN CLOB
) RETURN CLOB
IS
BEGIN
RETURN '<books><book><raw>' ||
       P_RAW_DATA ||
       '</raw></book></books>';
END;
FUNCTION PARSE_TO_JSON(
    P_RAW_DATA IN CLOB
) RETURN CLOB
IS
BEGIN
RETURN '{"books":[{"raw":"' ||
       P_RAW_DATA ||
       '"}]}';
END;
PROCEDURE INSERT_BOOKS(
    P_XML IN CLOB,
    P_JSON IN CLOB
)
IS
BEGIN

INSERT INTO AUTHORS(NAME)
VALUES('Sample Author');

INSERT INTO PUBLISHERS(NAME)
VALUES('Sample Publisher');

INSERT INTO BOOKS(
    TITLE,
    AUTHOR_ID,
    PUBLISHER_ID,
    ISBN,
    PUBLICATION_YEAR
)
VALUES(
          'Sample Book',
          (SELECT MAX(ID) FROM AUTHORS),
          (SELECT MAX(ID) FROM PUBLISHERS),
          '1111111111111',
          2026
      );

EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(
        -20001,
        SQLERRM
    );

END;
PROCEDURE GET_BOOKS(
    P_CURSOR OUT SYS_REFCURSOR
)
IS
BEGIN

OPEN P_CURSOR FOR

SELECT
    B.ID,
    B.TITLE,
    A.NAME AUTHOR_NAME,
    P.NAME PUBLISHER_NAME,
    B.ISBN,
    B.PUBLICATION_YEAR
FROM BOOKS B
         JOIN AUTHORS A
              ON B.AUTHOR_ID=A.ID
         JOIN PUBLISHERS P
              ON B.PUBLISHER_ID=P.ID;

END;
END BOOK_OPERATIONS;
/
