CREATE OR REPLACE PACKAGE BOOK_OPERATIONS AS

    PROCEDURE INSERT_BOOKS(
        P_XML IN CLOB,
        P_JSON IN CLOB
    );

    PROCEDURE GET_BOOKS(
        P_CURSOR OUT SYS_REFCURSOR
    );

END BOOK_OPERATIONS;
/